#!/usr/bin/env bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║             VIZIER - Claude Code Visualizer                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Horizontal Timeline Visualization:"
echo ""
echo "L0 ●──◉──⬢──✓──◉──⬢──✓──●──◉──"
echo "   │     │           └──────────┐"
echo "L1 │     └──⟐──⬢──⬢──✓──⟐       │"
echo "   │           │                │"
echo "L2 │           └──○──✓           │"
echo "   │                            │"
echo "   User starts conversation     Agent explores"
echo ""
echo "Legend:"
echo "  ● User      ◉ Assistant  ⬢ Tool   ✓ Success"
echo "  ✗ Error    ⟐ Agent      ○ Progress"
echo ""
echo "Controls:"
echo "  h/l or ←/→  Scroll timeline"
echo "  j/k or ↑/↓  Select nodes"
echo "  q           Quit"
echo ""
echo "Run: make dev"
